---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kongden-backend-v2-a5c3db8f          # Service name
  labels:
    app: kongden-backend-v2-a5c3db8f
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: kongden-backend-v2-a5c3db8f         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 8080         # Service port
      targetPort: 8080  # Target container port
